include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.chopper.dart
    - lib/**.graphql.dart
    - lib/shared/i18n.dart
    - ios/fastlane/README.md
  errors:
    todo: warning
    dead_code: info

linter:
  rules:
    - one_member_abstracts
    - await_only_futures
