name: flutter_scandit
description: Flutter Plugin for Scandit Barcode Scanning on Android and iOS
version: 1.0.0
homepage: https://github.com/fryette/flutter_scandit
repository: https://github.com/fryette/flutter_scandit
issue_tracker: https://github.com/fryette/flutter_scandit/issues

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.20.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lint: ^1.3.0-dev.d29.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: za.co.palota.flutter_scandit
        pluginClass: FlutterScanditPlugin