name: flutter_scandit
description: Flutter Plugin for Scandit Barcode Scanning on Android and iOS
version: 0.1.0
homepage: https://github.com/PalotaCompany/flutter_scandit

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lint: ^1.3.0-dev.d29.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: za.co.palota.flutter_scandit
    pluginClass: FlutterScanditPlugin
    
  assets:
   - assets/